import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const sourceRoot = resolve(root, "src");
const output = resolve(sourceRoot, "generated/icon-collection.ts");
const iconDataPath = resolve(root, "node_modules/@iconify-json/solar/icons.json");
const iconInfoPath = resolve(root, "node_modules/@iconify-json/solar/info.json");

function sourceFiles(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) return entry.name === "generated" ? [] : sourceFiles(path);
    return /\.[cm]?[jt]sx?$/.test(entry.name) && statSync(path).isFile() ? [path] : [];
  });
}

const names = new Set();
for (const file of sourceFiles(sourceRoot)) {
  const source = readFileSync(file, "utf8");
  for (const match of source.matchAll(/\b(solar|mdi):([a-z0-9-]+)\b/g)) {
    if (match[1] === "solar") names.add(match[2]);
    else throw new Error(`Non-Solar Iconify name ${match[0]} in ${file}`);
  }
}

const official = JSON.parse(readFileSync(iconDataPath, "utf8"));
const info = JSON.parse(readFileSync(iconInfoPath, "utf8"));
const icons = {};
for (const name of [...names].sort()) {
  const icon = official.icons[name];
  if (!icon) throw new Error(`Unknown Solar icon: ${name}`);
  icons[name] = icon;
}

const generated = `// Generated by scripts/generate_icon_collection.mjs.\n` +
  `// Contains only the Solar glyphs referenced by the SPA.\n` +
  `// Solar icons by ${info.author.name}; licensed ${info.license.title}.\n` +
  `// ${info.license.url}\n` +
  `export const weatherEdgeIcons = ${JSON.stringify({
    prefix: "solar",
    width: official.width,
    height: official.height,
    icons,
  }, null, 2)} as const;\n`;

if (process.argv.includes("--check")) {
  const current = readFileSync(output, "utf8");
  if (current !== generated) {
    throw new Error("Local icon collection is stale. Run `bun run icons:generate`.");
  }
} else {
  writeFileSync(output, generated);
  console.log(`Wrote ${Object.keys(icons).length} Solar icons to ${output}`);
}
